comfyui:
    base_path: /workspace/ComfyUI
    is_default: true
    custom_nodes: custom_nodes/
    input: input/
    animatediff_models: models/animatediff_models/
    checkpoints: models/checkpoints/
    clip: models/clip/
    clip_vision: models/clip_vision/
    configs: models/configs/
    controlnet: models/controlnet/
    diffusers: models/diffusers/
    diffusion_models: models/diffusion_models/
    embeddings: models/embeddings/
    gligen: models/gligen/
    hypernetworks: models/hypernetworks/
    ipadapter: models/ipadapter/
    loras: models/loras/
    photomaker: models/photomaker/
    sams: models/sams/
    style_models: models/style_models/
    text_encoders: models/text_encoders/
    ultralytics: models/ultralytics/
    unet: models/unet/
    upscale_models: models/upscale_models/
    vae: models/vae/
    vae_approx: models/vae_approx/
    user: user/
    workflows: workflows/
    
